title: GotoFinal
description: Java (mostly), my projects and diorite.
author: Bartłomiej Mazur
logo: /static/img/avatar.jpg
github: https://github.com/GotoFinal
about: About Java, my projects and diorite.
image: static/img/posts/prev.png

baseurl: ""
url: "https://blog.gotofinal.com"

allowsearch: true

#disqus_shortname: gotofinal
google_analytics: UA-100470162-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- run.sh
- update.sh